### ISSUE TITLE
Send the request on keyboard shortcut in while cursor is active on URL panel

### ISSUE THREAD

**Issue by kannananil** [req-io/req.io#36]
It would be easier for the users to trigger the request when enter key is pressed while the users cursor is on the URL panel input box.

- [x] Given the user opened the application and added valid URL and body
When the users cursor is active on the URL panel input box and pressed Enter key
Then the request should be triggered to the given URL with given body

- [x] Given the user opened the application and added an invalid URL or body
When the user cursor is active on the URL panel input box and pressed Enter key
Then the request should be triggered and display the Error message and Error Status

**Comment by pssruthy** [comment]
This issue is closed
