### ISSUE TITLE
Enable soft wrap for JSON editor used in request panel

### ISSUE THREAD

**Issue by kannananil** [req-io/req.io#45]
Currently the JSON editor on the request panel is vertically and horizontally scrollable incase the number or lines or length of a line increases. But when a length of a line increases scroll will not be a proper solution as it would not provide a proper view of the whole body as we scroll to the right side to see the long line.

So instead of the horizontal scrolling we would like to enable the softwrap in JSON viewer in response panel.

Reference document to [React Ace](https://github.com/securingsincity/react-ace/blob/master/docs/Ace.md#available-props) package

- [x] Given the user opened the application and added a request with body
When the length of line in the JSON body exceeds the width of the editor panel
The line should be wrapped down to the next line

**Comment by pssruthy** [comment]
This issue is closed
