### ISSUE TITLE
Raw response tab is not scrollable

### ISSUE THREAD

**Issue by kannananil** [req-io/req.io#47]
The Raw response tab is currently not scrollable, so when the response from the API exceeds a certain limit the users would not be able to view the full response.

As part of this issue we would like to fix this issue and make the Raw response panel vertically scrollable.

- [ ] Given the user triggered a request with proper request parameters
When the response received exceeds Raw response panel size
Then the user should be able to scroll down and see the remaining response

**Optional task**
- [ ] Update the styling and font family of the Raw response panel to make it consistent with the Response preview panel

<img width="1451" alt="Screenshot 2023-10-27 at 12 23 29 AM" src="https://github.com/req-io/req.io/assets/56071561/3e265014-446a-4ca6-8192-2b34053ce011">

**Comment by pssruthy** [comment]
This issue is closed
