### ISSUE TITLE
Enable soft wrap for JSON viewer used in response panel

### ISSUE THREAD

**Issue by kannananil** [req-io/req.io#49]
Currently the JSON viewer on the response panel is vertically and horizontally scrollable incase the number or lines or length of a line increases. But when a length of a line increases scroll will not be a proper solution as it would not provide a proper view of the whole body as we scroll to the right side to see the long line.

So instead of the horizontal scrolling we would like to enable the softwrap in response panel JSON viewer.

Reference document to [React Ace](https://github.com/securingsincity/react-ace/blob/master/docs/Ace.md#available-props) package

- [ ] Given the user triggered a request with proper payload and received a response
When the length of line in the response body exceeds the width of the JSON viewer panel
The line should be wrapped down to the next line

**Comment by pssruthy** [comment]
This issue is closed
